export const workExperience = [
  {
    company: "Harnois Énergies",
    role: "Développeur logiciel",
    startDate: "2025-06-23",
    endDate: "2025-12-01",
    description: [
      "Développement et amélioration de solutions internes.",
      "Intégration et automatisation de fonctionnalités.",
      "Collaboration avec les équipes pour livrer rapidement et proprement.",
    ],
    location: "Saint-Thomas",
    logo: "/images/entreprises/HE.png",
  },
  {
    company: "Consultant indépendant",
    role: "Consultant en intégration IA",
    startDate: "2025-01-06",
    endDate: "2025-07-11",
    description: [
      "Veille et évaluation d’outils IA pour développeurs.",
      "Prototypage, tests et recommandations.",
      "Documentation et synthèse des apprentissages.",
    ],
    location: "Québec",
    logo: "/icones/coffee-icon.ico",
  },
  {
    company: "Logiciels Sys-Thèmes inc.",
    role: "Développeur Full Stack",
    startDate: "2024-05-27",
    endDate: "2025-04-04",
    description: [
      "Migration d’un outil legacy vers Flexio® ERP.",
      "Développement backend Java et intégration BD.",
      "Implantation UI avec Kendo UI + tests avant déploiement.",
    ],
    location: "Terrebonne",
    logo: "/images/entreprises/systhemes.jpg",
  },
  {
    company: "Binder",
    role: "Stagiaire développeur Web et mobile",
    startDate: "2023-09-18",
    endDate: "2023-12-01",
    description: [
      "Authentification et features mobile (Svelte/SvelteKit).",
      "UI/UX (Figma) et intégration multilingue.",
      "Documentation et collaboration produit.",
    ],
    location: "Montréal",
    logo: "/images/entreprises/binder.jpg",
  },
  {
    company: "Industries Harnois inc.",
    role: "Programmeur CAO et gestionnaire projets",
    startDate: "2008-06-02",
    endDate: "2022-08-26",
    description: [
      "Gestionnaire de projets d'envergure.",
      "Programmation sur PTC Creo.",
      "Intégration et optimisation Windchill PLM.",
    ],
    location: "Saint-Thomas",
    logo: "/images/entreprises/Harnois.jpg",
  },
];
